services:
  - type: web
    name: mypusher
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: SELF_PING_URL
        sync: false
